image: ruby:2.3

pages:
  script:
  - apt-get update
  - apt-get install -y pandoc
  - gem install jekyll
  - gem install pandoc-ruby
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
